### ISSUE TITLE
AWS_LAMBDA_RUNTIME_API is hardcoded and can't be overwritten

### ISSUE THREAD

**Issue by Hi-Fi** [triggermesh/aws-custom-runtime#14]
If InternalAPIport is changed to something else than 80 (which is the default value), functions are not starting because `AWS_LAMBDA_RUNTIME_API` is hardcoded to be just [`127.0.0.1`](https://github.com/triggermesh/aws-custom-runtime/blob/master/main.go#L76). 

`AWS_LAMBDA_RUNTIME_API` should probably be `127.0.0.1:<InternalAPIport>`?

Relates to triggermesh/knative-lambda-runtime#48

**Comment by tzununbekov** [comment]
@Hi-Fi hey, is it possible for you to check if changes in #15 solve the problem or you need to have the prebuilt KLR image to test it?

**Comment by Hi-Fi** [comment]
Seems to be working fine. Replaced in go example Dockerfile's
`go get github.com/triggermesh/aws-custom-runtime`with `GO111MODULE=on go get github.com/triggermesh/aws-custom-runtime@ef74027b321f3b1df486614ebfb64552c69f8506`.
